# Generated by Django 4.2.11 on 2026-04-21 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('assistant', 'Ассистент')], max_length=16)),
                ('content', models.TextField()),
                ('workout_suggestion', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_chat_messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='ai_chat_mes_user_id_12ed95_idx')],
            },
        ),
    ]
