# Generated by Django 4.2.11 on 2026-05-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='workout_imports',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
