# Generated by Django 4.2.11 on 2026-04-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='parameters',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
