# Generated by Django 4.2.11 on 2026-05-15 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_workout_date_datefield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutexercise',
            options={'ordering': ['order', 'id']},
        ),
    ]
