# Generated by Django 4.2.11 on 2026-04-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(choices=[('lose_weight', 'Снижение веса'), ('gain_muscle', 'Набор мышечной массы'), ('recomposition', 'Рекомпозиция тела'), ('improve_endurance', 'Улучшение выносливости'), ('increase_strength', 'Увеличение силы'), ('maintain', 'Поддержание формы')], default='maintain', max_length=50, verbose_name='Цель тренировок'),
        ),
    ]
