# Generated by Django 4.2.11 on 2026-04-07 07:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('equipment', models.CharField(blank=True, max_length=255, null=True)),
                ('target_muscles', models.JSONField(default=list)),
                ('tags', models.JSONField(default=list)),
                ('images', models.JSONField(default=list)),
                ('source_file', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exercises',
            },
        ),
        migrations.CreateModel(
            name='ExerciseParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('weight', 'Вес'), ('reps', 'Повторения'), ('sets', 'Подходы'), ('time', 'Время'), ('distance', 'Расстояние')], max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='exercises.exercise')),
            ],
            options={
                'db_table': 'exercise_parameters',
            },
        ),
    ]
