# Generated by Django 4.2.11 on 2026-04-11 19:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название снаряжения')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('tags', models.JSONField(default=list, verbose_name='Теги')),
                ('image', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL изображения')),
                ('source_file', models.CharField(blank=True, max_length=255, null=True, verbose_name='Исходный файл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Снаряжение',
                'verbose_name_plural': 'Снаряжение',
                'db_table': 'equipment',
            },
        ),
    ]
